//! Build script: Tauri's own build, with the app's command list.
//!
//! Tauri only checks app commands against the capabilities once the
//! app declares its commands. Without that declaration any page that
//! ends up in one of our windows, our own or not, can call every
//! command. So the list is declared here, read from the
//! `generate_handler!` block in src/lib.rs so there is one list to keep,
//! and a permission set granting them is written for
//! capabilities/default.json, which hands them to our own pages only.

use std::fmt::Write as _;
use std::path::Path;

/// Every command registered in `generate_handler![...]`, by name.
fn registered_commands() -> Vec<String> {
    let source = std::fs::read_to_string("src/lib.rs").expect("read src/lib.rs");
    let start = source
        .find("generate_handler![")
        .expect("lib.rs registers its commands with generate_handler!")
        + "generate_handler![".len();
    let end = start
        + source[start..]
            .find("])")
            .expect("generate_handler! is closed");
    source[start..end]
        .lines()
        .map(|line| line.split("//").next().unwrap_or(""))
        .flat_map(|line| line.split(','))
        .map(str::trim)
        .filter(|item| !item.is_empty())
        .map(|item| {
            assert!(
                item.chars()
                    .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == ':'),
                "unexpected entry in generate_handler!: {item}"
            );
            item.rsplit("::").next().unwrap_or(item).to_string()
        })
        .collect()
}

/// The permission set the capability grants: allow every registered
/// command. Rewritten only when it changes, so it does not trigger a
/// rebuild of its own.
fn write_permission_set(commands: &[String]) {
    let mut text = String::from(
        "# Generated by build.rs from the generate_handler! list in src/lib.rs.\n\
         # Do not edit; register or remove a command there instead.\n\n\
         [[set]]\n\
         identifier = \"app-commands\"\n\
         description = \"Every command the app registers, for the app's own pages.\"\n\
         permissions = [\n",
    );
    for command in commands {
        let _ = writeln!(text, "  \"allow-{}\",", command.replace('_', "-"));
    }
    text.push_str("]\n");
    let path = Path::new("permissions/app-commands.toml");
    if std::fs::read_to_string(path).ok().as_deref() != Some(text.as_str()) {
        std::fs::create_dir_all("permissions").expect("make permissions/");
        std::fs::write(path, text).expect("write permissions/app-commands.toml");
    }
}

fn main() {
    println!("cargo:rerun-if-changed=src/lib.rs");
    let commands = registered_commands();
    write_permission_set(&commands);
    // The manifest wants a list that lives for the whole build; a build
    // script runs once and exits, so leaking it is the plain way.
    let names: Vec<&'static str> = commands
        .into_iter()
        .map(|c| &*Box::leak(c.into_boxed_str()))
        .collect();
    let names: &'static [&'static str] = Box::leak(names.into_boxed_slice());
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(names)),
    )
    .expect("tauri build");
}
