//! The click, generated by the engine.
//!
//! It used to be a WebAudio oscillator inside the WebView, scheduled from a
//! React effect that watched the playhead. That has two consequences a
//! producer feels immediately: the click drifts against the audio the engine
//! is actually playing, because the two run on different clocks and the UI
//! only learns the position a few times a second; and it can never appear in
//! anything the engine renders, because the engine has never heard of it.
//!
//! Here the click is placed from the same sample position the audio uses, so
//! a beat lands exactly on its sample.

use hardwave_project::tempo::TempoMap;
use std::sync::atomic::{AtomicBool, AtomicU32, Ordering};
use std::sync::Arc;

/// How the click sounds. Matches the WebAudio one it replaces so it is not a
/// surprise to anyone who was already using it: a short sine blip, higher on
/// the downbeat.
const DOWNBEAT_HZ: f32 = 1500.0;
const BEAT_HZ: f32 = 800.0;
/// Decay to near silence in 55 ms, as the old one did.
const DECAY_SECS: f32 = 0.055;

/// Shared settings, written by the UI thread and read on the audio thread.
#[derive(Clone)]
pub struct MetronomeSettings {
    pub enabled: Arc<AtomicBool>,
    /// Linear gain in f32 bits.
    pub volume: Arc<AtomicU32>,
    /// Accent the first beat of the bar.
    pub accent: Arc<AtomicBool>,
    /// Only click while recording.
    pub record_only: Arc<AtomicBool>,
}

impl MetronomeSettings {
    pub fn new() -> Self {
        Self {
            enabled: Arc::new(AtomicBool::new(false)),
            volume: Arc::new(AtomicU32::new(0.7f32.to_bits())),
            accent: Arc::new(AtomicBool::new(true)),
            record_only: Arc::new(AtomicBool::new(false)),
        }
    }

    /// Settings that can never make a sound, for the offline renderer.
    ///
    /// A bounce must not contain the click: it is a guide for the person
    /// playing, not part of the music. Using a separate, permanently disabled
    /// instance means an export cannot pick one up by accident, whatever the
    /// user has switched on for playback.
    pub fn silent() -> Self {
        let s = Self::new();
        s.enabled.store(false, Ordering::Relaxed);
        s
    }

    pub fn volume_linear(&self) -> f32 {
        f32::from_bits(self.volume.load(Ordering::Relaxed)).clamp(0.0, 4.0)
    }

    pub fn set_volume_linear(&self, v: f32) {
        self.volume
            .store(v.clamp(0.0, 4.0).to_bits(), Ordering::Relaxed);
    }

    pub fn is_audible(&self, recording: bool) -> bool {
        self.enabled.load(Ordering::Relaxed)
            && (!self.record_only.load(Ordering::Relaxed) || recording)
    }
}

impl Default for MetronomeSettings {
    fn default() -> Self {
        Self::new()
    }
}

/// One click, decaying. Kept as state so a blip that started near the end of
/// a block finishes properly in the next one instead of being cut off.
#[derive(Default)]
pub struct ClickVoice {
    phase: f32,
    phase_step: f32,
    remaining: u32,
    total: u32,
    gain: f32,
}

impl ClickVoice {
    fn start(&mut self, freq: f32, gain: f32, sample_rate: f32) {
        self.phase = 0.0;
        self.phase_step = std::f32::consts::TAU * freq / sample_rate;
        self.total = (DECAY_SECS * sample_rate) as u32;
        self.remaining = self.total;
        self.gain = gain;
    }

    fn next_sample(&mut self) -> f32 {
        if self.remaining == 0 || self.total == 0 {
            return 0.0;
        }
        // Exponential-ish decay, matching the old ramp to near silence.
        let t = 1.0 - (self.remaining as f32 / self.total as f32);
        let env = (1.0 - t).powf(3.0);
        let s = self.phase.sin() * env * self.gain;
        self.phase += self.phase_step;
        self.remaining -= 1;
        s
    }
}

/// One click the engine has placed inside the block being rendered.
#[derive(Debug, Clone, Copy)]
pub struct ClickEvent {
    /// Frame inside this block where the click starts.
    pub frame_offset: usize,
    /// Accent it as a bar's first beat.
    pub downbeat: bool,
}

/// How many clicks one block can hold.
///
/// Sixteenths at 300 bpm in a 1024-frame block at 48 kHz is four, so this is
/// more than a musical tempo needs and keeps the schedule on the stack.
pub const MAX_CLICKS_PER_BLOCK: usize = 16;

/// Fill `out` with the beats that fall inside one block.
///
/// Returns how many entries were filled. The beats come from the project's
/// tempo map, which is what makes the click follow a tempo change, a ramp, an
/// eighth-note signature and a signature change part-way through the song.
///
/// Every beat belongs to exactly one block: a beat is placed when its sample
/// is inside `[start, start + num_frames)`, so consecutive blocks neither
/// repeat a beat nor drop one.
pub fn schedule_block_clicks(
    map: &TempoMap,
    start: u64,
    num_frames: usize,
    sample_rate: f64,
    out: &mut [ClickEvent],
) -> usize {
    if sample_rate <= 0.0 || num_frames == 0 || out.is_empty() {
        return 0;
    }
    let end = start + num_frames as u64;
    let start_tick = map.samples_to_tick(start, sample_rate);
    // Search from a beat earlier: the tick for `start` is rounded, so a beat
    // sitting exactly on the block boundary can land just behind it, and
    // starting the walk at `start_tick` would step over that beat entirely.
    let per_beat = map.beat_grid_at(start_tick).ticks_per_beat.max(1);
    let mut tick = start_tick.saturating_sub(per_beat);

    let mut count = 0;
    while count < out.len() {
        let (beat_tick, downbeat) = map.next_beat_at_or_after(tick);
        let sample = map.tick_to_samples(beat_tick, sample_rate);
        if sample >= end {
            break;
        }
        if sample >= start {
            out[count] = ClickEvent {
                frame_offset: (sample - start) as usize,
                downbeat,
            };
            count += 1;
        }
        tick = beat_tick + 1;
    }
    count
}

/// Places clicks on beats and renders them.
pub struct Metronome {
    settings: MetronomeSettings,
    voice: ClickVoice,
}

impl Metronome {
    pub fn new(settings: MetronomeSettings) -> Self {
        Self {
            settings,
            voice: ClickVoice::default(),
        }
    }

    pub fn settings(&self) -> &MetronomeSettings {
        &self.settings
    }

    /// Mix the block's scheduled clicks into an interleaved stereo buffer.
    ///
    /// The schedule comes from the engine, which reads the project's tempo
    /// map. This used to work the beats out here from samples-per-beat and one
    /// beats-per-bar number, which can only be right for a song at one tempo,
    /// in one signature, counted in quarter notes: a 7/8 section clicked in
    /// quarters, a signature change never moved the accent, and a tempo change
    /// slid the whole click grid off the music.
    pub fn render_scheduled(
        &mut self,
        output: &mut [f32],
        num_frames: usize,
        events: &[ClickEvent],
        recording: bool,
        sample_rate: f64,
    ) {
        let audible = self.settings.is_audible(recording);
        if !audible && self.voice.remaining == 0 {
            return;
        }
        if sample_rate <= 0.0 {
            return;
        }
        let volume = self.settings.volume_linear();
        let accent = self.settings.accent.load(Ordering::Relaxed);

        let mut next = 0usize;
        for frame in 0..num_frames {
            if audible {
                while next < events.len() && events[next].frame_offset == frame {
                    let freq = if accent && events[next].downbeat {
                        DOWNBEAT_HZ
                    } else {
                        BEAT_HZ
                    };
                    self.voice.start(freq, volume * 0.6, sample_rate as f32);
                    next += 1;
                }
            }
            let s = self.voice.next_sample();
            if s != 0.0 {
                let i = frame * 2;
                if i + 1 < output.len() {
                    output[i] += s;
                    output[i + 1] += s;
                }
            }
        }
    }
}

impl Metronome {
    /// Render the count-in for one block.
    ///
    /// `elapsed` is how many samples of the count-in have already passed, so
    /// the beats are placed from the same clock that decides when playback
    /// starts. The count-in clicks even when the metronome is switched off
    /// for playback: asking for a count-in IS asking to hear it, and a silent
    /// count-in is just a delay.
    ///
    /// `samples_per_beat` rather than a tempo, because a beat is a note value:
    /// in 7/8 a beat is an eighth note, and deriving it from the tempo alone
    /// counted the bar in quarters and made the count-in twice as long as the
    /// bar it was counting in.
    pub fn render_count_in(
        &mut self,
        output: &mut [f32],
        num_frames: usize,
        elapsed: u64,
        samples_per_beat: f64,
        beats_per_bar: u32,
        sample_rate: f64,
    ) {
        if sample_rate <= 0.0 || samples_per_beat < 1.0 {
            return;
        }
        let volume = self.settings.volume_linear();
        let accent = self.settings.accent.load(Ordering::Relaxed);
        let bar = beats_per_bar.max(1) as u64;

        for frame in 0..num_frames {
            let pos = elapsed + frame as u64;
            let beat_now = (pos as f64 / samples_per_beat).floor() as i64;
            let beat_prev = if pos == 0 {
                -1
            } else {
                ((pos - 1) as f64 / samples_per_beat).floor() as i64
            };
            if beat_now != beat_prev && beat_now >= 0 {
                let downbeat = accent && (beat_now as u64).is_multiple_of(bar);
                let freq = if downbeat { DOWNBEAT_HZ } else { BEAT_HZ };
                self.voice.start(freq, volume * 0.6, sample_rate as f32);
            }
            let s = self.voice.next_sample();
            if s != 0.0 {
                let i = frame * 2;
                if i + 1 < output.len() {
                    output[i] += s;
                    output[i + 1] += s;
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const SR: f64 = 48_000.0;

    fn beat_at(frame_offset: usize, downbeat: bool) -> ClickEvent {
        ClickEvent {
            frame_offset,
            downbeat,
        }
    }

    fn render_block(m: &mut Metronome, frames: usize, events: &[ClickEvent]) -> Vec<f32> {
        let mut out = vec![0.0f32; frames * 2];
        m.render_scheduled(&mut out, frames, events, false, SR);
        out
    }

    /// The sample index of the first non-silent frame, which is where the
    /// beat actually landed.
    fn first_click_frame(out: &[f32]) -> Option<usize> {
        out.chunks(2).position(|c| c[0].abs() > 1e-6)
    }

    #[test]
    fn a_beat_lands_on_its_exact_sample() {
        let settings = MetronomeSettings::new();
        settings.enabled.store(true, Ordering::Relaxed);
        let mut m = Metronome::new(settings);

        // A beat the engine placed 100 frames into this block.
        let out = render_block(&mut m, 512, &[beat_at(100, true)]);

        // The voice starts at frame 100, and a sine begins at zero, so the
        // first sample you can measure is 101. What matters is that it is
        // there and not tens of milliseconds later, which is what a click
        // scheduled from UI ticks looked like.
        let first = first_click_frame(&out).expect("the beat must click");
        assert!(
            (100..=101).contains(&first),
            "click landed at frame {first}, not on the beat at 100"
        );
        assert!(
            out[..200].iter().all(|s| *s == 0.0),
            "nothing may sound before the beat"
        );
    }

    #[test]
    fn the_click_is_silent_when_switched_off() {
        let mut m = Metronome::new(MetronomeSettings::new());
        let out = render_block(&mut m, 512, &[beat_at(0, true)]);
        assert!(out.iter().all(|s| *s == 0.0));
    }

    #[test]
    fn record_only_stays_quiet_until_recording() {
        let settings = MetronomeSettings::new();
        settings.enabled.store(true, Ordering::Relaxed);
        settings.record_only.store(true, Ordering::Relaxed);
        let mut m = Metronome::new(settings);

        let mut playback = vec![0.0f32; 512 * 2];
        m.render_scheduled(&mut playback, 512, &[beat_at(0, true)], false, SR);
        assert!(
            playback.iter().all(|s| *s == 0.0),
            "record-only must not click during plain playback"
        );

        let mut recording = vec![0.0f32; 512 * 2];
        m.render_scheduled(&mut recording, 512, &[beat_at(0, true)], true, SR);
        assert!(recording.iter().any(|s| s.abs() > 1e-6));
    }

    #[test]
    fn the_downbeat_is_higher_than_the_other_beats() {
        let settings = MetronomeSettings::new();
        settings.enabled.store(true, Ordering::Relaxed);
        let mut m = Metronome::new(settings);

        // Zero crossings over the first 5 ms tell the two pitches apart.
        let crossings = |out: &[f32]| {
            let mono: Vec<f32> = out.chunks(2).map(|c| c[0]).take(240).collect();
            mono.windows(2)
                .filter(|w| w[0] <= 0.0 && w[1] > 0.0)
                .count()
        };
        let down = render_block(&mut m, 512, &[beat_at(0, true)]);
        let mut m2 = Metronome::new({
            let s = MetronomeSettings::new();
            s.enabled.store(true, Ordering::Relaxed);
            s
        });
        let other = render_block(&mut m2, 512, &[beat_at(0, false)]);

        assert!(
            crossings(&down) > crossings(&other),
            "downbeat {} should be higher pitched than beat {}",
            crossings(&down),
            crossings(&other)
        );
    }

    #[test]
    fn a_click_started_late_in_a_block_finishes_in_the_next_one() {
        let settings = MetronomeSettings::new();
        settings.enabled.store(true, Ordering::Relaxed);
        let mut m = Metronome::new(settings);

        // A beat two frames before the end of a four-frame block.
        let first = render_block(&mut m, 4, &[beat_at(2, false)]);
        assert!(first.iter().any(|s| s.abs() > 1e-6));

        // The tail continues rather than being cut off mid-blip.
        let second = render_block(&mut m, 512, &[]);
        assert!(
            second.iter().take(64).any(|s| s.abs() > 1e-6),
            "the click must carry over the block boundary"
        );
    }

    #[test]
    fn the_count_in_clicks_from_its_own_start_not_the_song_position() {
        // Switched OFF for playback on purpose: asking for a count-in is
        // asking to hear it, whatever the click is set to afterwards.
        let mut m = Metronome::new(MetronomeSettings::new());

        let mut out = vec![0.0f32; 512 * 2];
        // 120 bpm at 48 kHz: 24000 samples per beat.
        m.render_count_in(&mut out, 512, 0, 24_000.0, 4, SR);

        assert!(
            out.iter().any(|s| s.abs() > 1e-6),
            "the count-in must be audible even with the click switched off"
        );
        assert_eq!(
            first_click_frame(&out),
            Some(1),
            "the first count-in beat belongs at the very start"
        );
    }

    #[test]
    fn count_in_beats_are_one_beat_apart() {
        let mut m = Metronome::new(MetronomeSettings::new());

        // Second beat of a 120 bpm count-in is 24000 samples in.
        let mut out = vec![0.0f32; 512 * 2];
        m.render_count_in(&mut out, 512, 24_000 - 50, 24_000.0, 4, SR);

        let first = first_click_frame(&out).expect("beat two must click");
        assert!(
            (50..=51).contains(&first),
            "count-in beat landed at {first}, not at 50"
        );
    }

    // ---- scheduling -------------------------------------------------------

    use hardwave_project::tempo::{TempoEntry, TempoRamp};

    const PPQ: u64 = 960;

    fn map(entries: Vec<(u64, f64, u32, u32)>) -> TempoMap {
        TempoMap {
            entries: entries
                .into_iter()
                .map(|(tick, bpm, num, den)| TempoEntry {
                    tick,
                    bpm,
                    time_sig_num: num,
                    time_sig_den: den,
                    ramp: TempoRamp::Instant,
                })
                .collect(),
        }
    }

    fn schedule(map: &TempoMap, start: u64, frames: usize) -> Vec<ClickEvent> {
        let mut out = [ClickEvent {
            frame_offset: 0,
            downbeat: false,
        }; MAX_CLICKS_PER_BLOCK];
        let n = schedule_block_clicks(map, start, frames, SR, &mut out);
        out[..n].to_vec()
    }

    #[test]
    fn the_first_beat_of_the_song_is_a_downbeat_at_frame_zero() {
        let m = map(vec![(0, 120.0, 4, 4)]);
        let events = schedule(&m, 0, 512);
        assert_eq!(events.len(), 1);
        assert_eq!(events[0].frame_offset, 0);
        assert!(events[0].downbeat);
    }

    #[test]
    fn a_beat_is_placed_at_its_own_sample_inside_the_block() {
        // 120 bpm at 48 kHz: a beat every 24000 samples.
        let m = map(vec![(0, 120.0, 4, 4)]);
        let events = schedule(&m, 24_000 - 100, 512);
        assert_eq!(events.len(), 1);
        assert_eq!(events[0].frame_offset, 100);
        assert!(!events[0].downbeat, "beat 2 is not a downbeat");
    }

    #[test]
    fn every_beat_is_clicked_exactly_once_across_consecutive_blocks() {
        let m = map(vec![(0, 120.0, 4, 4)]);
        let frames = 512;
        let mut clicks = 0;
        let mut downbeats = 0;
        // 8 beats at 120 bpm is 192000 samples, so walk a little past it.
        for block in 0..400 {
            for event in schedule(&m, block * frames as u64, frames) {
                assert!(event.frame_offset < frames);
                clicks += 1;
                if event.downbeat {
                    downbeats += 1;
                }
            }
        }
        // 400 blocks of 512 frames is 204800 samples: beats 0..8 land inside.
        assert_eq!(clicks, 9, "a beat was dropped or clicked twice");
        assert_eq!(downbeats, 3, "downbeats on beats 0, 4 and 8");
    }

    #[test]
    fn an_eighth_note_signature_clicks_eighths() {
        // 7/8 at 120 bpm: an eighth is 12000 samples, the bar is 84000.
        let m = map(vec![(0, 120.0, 7, 8)]);
        let events = schedule(&m, 0, 12_001);
        let offsets: Vec<usize> = events.iter().map(|e| e.frame_offset).collect();
        assert_eq!(offsets, vec![0, 12_000]);
        assert!(events[0].downbeat);
        assert!(!events[1].downbeat);
    }

    #[test]
    fn a_signature_change_part_way_through_gets_its_own_downbeat() {
        // 4/4 for 4 bars, then 7/8. At 120 bpm bar 5 starts at 16 beats,
        // which is 384000 samples.
        let m = map(vec![(0, 120.0, 4, 4), (PPQ * 16, 120.0, 7, 8)]);
        let events = schedule(&m, 384_000, 256);
        assert_eq!(events.len(), 1);
        assert_eq!(events[0].frame_offset, 0);
        assert!(events[0].downbeat, "the change starts a bar");

        // The next click is an eighth later, not a quarter.
        let next = schedule(&m, 384_000 + 256, 12_000);
        assert_eq!(next.len(), 1);
        assert_eq!(next[0].frame_offset, 12_000 - 256);
    }

    #[test]
    fn the_click_follows_a_tempo_change() {
        // 120 bpm for 4 beats, then 60 bpm: beats stop being 24000 apart.
        let m = map(vec![(0, 120.0, 4, 4), (PPQ * 4, 60.0, 4, 4)]);
        let after_change = 4 * 24_000;
        let events = schedule(&m, after_change, 48_001);
        let offsets: Vec<usize> = events.iter().map(|e| e.frame_offset).collect();
        // At 60 bpm a beat is 48000 samples, so the next one is a beat later.
        assert_eq!(offsets, vec![0, 48_000]);
    }

    #[test]
    fn a_block_with_no_beat_in_it_schedules_nothing() {
        let m = map(vec![(0, 120.0, 4, 4)]);
        assert!(schedule(&m, 1_000, 512).is_empty());
    }

    #[test]
    fn an_offline_render_can_never_click() {
        let silent = MetronomeSettings::silent();
        // Even if something switches it on, the export path holds its own
        // instance, so a bounce cannot inherit the playback setting.
        assert!(!silent.is_audible(true));
    }
}
