//! The click, generated by the engine.
//!
//! It used to be a WebAudio oscillator inside the WebView, scheduled from a
//! React effect that watched the playhead. That has two consequences a
//! producer feels immediately: the click drifts against the audio the engine
//! is actually playing, because the two run on different clocks and the UI
//! only learns the position a few times a second; and it can never appear in
//! anything the engine renders, because the engine has never heard of it.
//!
//! Here the click is placed from the same sample position the audio uses, so
//! a beat lands exactly on its sample.

use std::sync::atomic::{AtomicBool, AtomicU32, Ordering};
use std::sync::Arc;

/// How the click sounds. Matches the WebAudio one it replaces so it is not a
/// surprise to anyone who was already using it: a short sine blip, higher on
/// the downbeat.
const DOWNBEAT_HZ: f32 = 1500.0;
const BEAT_HZ: f32 = 800.0;
/// Decay to near silence in 55 ms, as the old one did.
const DECAY_SECS: f32 = 0.055;

/// Shared settings, written by the UI thread and read on the audio thread.
#[derive(Clone)]
pub struct MetronomeSettings {
    pub enabled: Arc<AtomicBool>,
    /// Linear gain in f32 bits.
    pub volume: Arc<AtomicU32>,
    /// Accent the first beat of the bar.
    pub accent: Arc<AtomicBool>,
    /// Only click while recording.
    pub record_only: Arc<AtomicBool>,
}

impl MetronomeSettings {
    pub fn new() -> Self {
        Self {
            enabled: Arc::new(AtomicBool::new(false)),
            volume: Arc::new(AtomicU32::new(0.7f32.to_bits())),
            accent: Arc::new(AtomicBool::new(true)),
            record_only: Arc::new(AtomicBool::new(false)),
        }
    }

    /// Settings that can never make a sound, for the offline renderer.
    ///
    /// A bounce must not contain the click: it is a guide for the person
    /// playing, not part of the music. Using a separate, permanently disabled
    /// instance means an export cannot pick one up by accident, whatever the
    /// user has switched on for playback.
    pub fn silent() -> Self {
        let s = Self::new();
        s.enabled.store(false, Ordering::Relaxed);
        s
    }

    pub fn volume_linear(&self) -> f32 {
        f32::from_bits(self.volume.load(Ordering::Relaxed)).clamp(0.0, 4.0)
    }

    pub fn set_volume_linear(&self, v: f32) {
        self.volume
            .store(v.clamp(0.0, 4.0).to_bits(), Ordering::Relaxed);
    }

    pub fn is_audible(&self, recording: bool) -> bool {
        self.enabled.load(Ordering::Relaxed)
            && (!self.record_only.load(Ordering::Relaxed) || recording)
    }
}

impl Default for MetronomeSettings {
    fn default() -> Self {
        Self::new()
    }
}

/// One click, decaying. Kept as state so a blip that started near the end of
/// a block finishes properly in the next one instead of being cut off.
#[derive(Default)]
pub struct ClickVoice {
    phase: f32,
    phase_step: f32,
    remaining: u32,
    total: u32,
    gain: f32,
}

impl ClickVoice {
    fn start(&mut self, freq: f32, gain: f32, sample_rate: f32) {
        self.phase = 0.0;
        self.phase_step = std::f32::consts::TAU * freq / sample_rate;
        self.total = (DECAY_SECS * sample_rate) as u32;
        self.remaining = self.total;
        self.gain = gain;
    }

    fn next_sample(&mut self) -> f32 {
        if self.remaining == 0 || self.total == 0 {
            return 0.0;
        }
        // Exponential-ish decay, matching the old ramp to near silence.
        let t = 1.0 - (self.remaining as f32 / self.total as f32);
        let env = (1.0 - t).powf(3.0);
        let s = self.phase.sin() * env * self.gain;
        self.phase += self.phase_step;
        self.remaining -= 1;
        s
    }
}

/// Places clicks on beats and renders them.
pub struct Metronome {
    settings: MetronomeSettings,
    voice: ClickVoice,
}

impl Metronome {
    pub fn new(settings: MetronomeSettings) -> Self {
        Self {
            settings,
            voice: ClickVoice::default(),
        }
    }

    pub fn settings(&self) -> &MetronomeSettings {
        &self.settings
    }

    /// Mix the click for one block into an interleaved stereo buffer.
    ///
    /// `position` is the playhead in samples at the START of the block, which
    /// is what makes the timing exact: every beat inside the block is placed
    /// at its own sample offset rather than whenever a UI tick noticed it.
    pub fn render(
        &mut self,
        output: &mut [f32],
        num_frames: usize,
        position: u64,
        bpm: f64,
        beats_per_bar: u32,
        sample_rate: f64,
        playing: bool,
        recording: bool,
    ) {
        let audible = self.settings.is_audible(recording);
        if !audible && self.voice.remaining == 0 {
            return;
        }
        if sample_rate <= 0.0 || bpm <= 0.0 {
            return;
        }

        let samples_per_beat = 60.0 / bpm * sample_rate;
        if samples_per_beat < 1.0 {
            return;
        }
        let volume = self.settings.volume_linear();
        let accent = self.settings.accent.load(Ordering::Relaxed);
        let bar = beats_per_bar.max(1) as u64;

        for frame in 0..num_frames {
            if audible && playing {
                let pos = position + frame as u64;
                // A beat starts in this sample when the sample index crosses
                // a multiple of the beat length.
                let beat_now = (pos as f64 / samples_per_beat).floor() as i64;
                let beat_prev = if pos == 0 {
                    -1
                } else {
                    ((pos - 1) as f64 / samples_per_beat).floor() as i64
                };
                if beat_now != beat_prev && beat_now >= 0 {
                    let downbeat = accent && (beat_now as u64) % bar == 0;
                    let freq = if downbeat { DOWNBEAT_HZ } else { BEAT_HZ };
                    self.voice.start(freq, volume * 0.6, sample_rate as f32);
                }
            }
            let s = self.voice.next_sample();
            if s != 0.0 {
                let i = frame * 2;
                if i + 1 < output.len() {
                    output[i] += s;
                    output[i + 1] += s;
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const SR: f64 = 48_000.0;

    fn render_block(m: &mut Metronome, frames: usize, position: u64, bpm: f64) -> Vec<f32> {
        let mut out = vec![0.0f32; frames * 2];
        m.render(&mut out, frames, position, bpm, 4, SR, true, false);
        out
    }

    /// The sample index of the first non-silent frame, which is where the
    /// beat actually landed.
    fn first_click_frame(out: &[f32]) -> Option<usize> {
        out.chunks(2).position(|c| c[0].abs() > 1e-6)
    }

    #[test]
    fn a_beat_lands_on_its_exact_sample() {
        let settings = MetronomeSettings::new();
        settings.enabled.store(true, Ordering::Relaxed);
        let mut m = Metronome::new(settings);

        // 120 bpm at 48 kHz is 24000 samples per beat. Render the block that
        // contains beat 4 (sample 96000) starting 100 samples early.
        let out = render_block(&mut m, 512, 96_000 - 100, 120.0);

        // The voice starts at frame 100, and a sine begins at zero, so the
        // first sample you can measure is 101. What matters is that it is
        // there and not tens of milliseconds later, which is what a click
        // scheduled from UI ticks looked like.
        let first = first_click_frame(&out).expect("the beat must click");
        assert!(
            (100..=101).contains(&first),
            "click landed at frame {first}, not on the beat at 100"
        );
        assert!(
            out[..200].iter().all(|s| *s == 0.0),
            "nothing may sound before the beat"
        );
    }

    #[test]
    fn the_click_is_silent_when_switched_off() {
        let mut m = Metronome::new(MetronomeSettings::new());
        let out = render_block(&mut m, 512, 0, 120.0);
        assert!(out.iter().all(|s| *s == 0.0));
    }

    #[test]
    fn record_only_stays_quiet_until_recording() {
        let settings = MetronomeSettings::new();
        settings.enabled.store(true, Ordering::Relaxed);
        settings.record_only.store(true, Ordering::Relaxed);
        let mut m = Metronome::new(settings);

        let mut playback = vec![0.0f32; 512 * 2];
        m.render(&mut playback, 512, 0, 120.0, 4, SR, true, false);
        assert!(
            playback.iter().all(|s| *s == 0.0),
            "record-only must not click during plain playback"
        );

        let mut recording = vec![0.0f32; 512 * 2];
        m.render(&mut recording, 512, 0, 120.0, 4, SR, true, true);
        assert!(recording.iter().any(|s| s.abs() > 1e-6));
    }

    #[test]
    fn the_downbeat_is_higher_than_the_other_beats() {
        let settings = MetronomeSettings::new();
        settings.enabled.store(true, Ordering::Relaxed);
        let mut m = Metronome::new(settings);

        // Zero crossings over the first 5 ms tell the two pitches apart.
        let crossings = |out: &[f32]| {
            let mono: Vec<f32> = out.chunks(2).map(|c| c[0]).take(240).collect();
            mono.windows(2)
                .filter(|w| w[0] <= 0.0 && w[1] > 0.0)
                .count()
        };
        let down = render_block(&mut m, 512, 0, 120.0);
        let mut m2 = Metronome::new({
            let s = MetronomeSettings::new();
            s.enabled.store(true, Ordering::Relaxed);
            s
        });
        let other = render_block(&mut m2, 512, 24_000, 120.0);

        assert!(
            crossings(&down) > crossings(&other),
            "downbeat {} should be higher pitched than beat {}",
            crossings(&down),
            crossings(&other)
        );
    }

    #[test]
    fn a_click_started_late_in_a_block_finishes_in_the_next_one() {
        let settings = MetronomeSettings::new();
        settings.enabled.store(true, Ordering::Relaxed);
        let mut m = Metronome::new(settings);

        // Beat at sample 24000, with only 4 frames left in this block.
        let first = render_block(&mut m, 4, 24_000 - 2, 120.0);
        assert!(first.iter().any(|s| s.abs() > 1e-6));

        // The tail continues rather than being cut off mid-blip.
        let second = render_block(&mut m, 512, 24_000 + 2, 120.0);
        assert!(
            second.iter().take(64).any(|s| s.abs() > 1e-6),
            "the click must carry over the block boundary"
        );
    }

    #[test]
    fn an_offline_render_can_never_click() {
        let silent = MetronomeSettings::silent();
        // Even if something switches it on, the export path holds its own
        // instance, so a bounce cannot inherit the playback setting.
        assert!(!silent.is_audible(true));
    }
}
